name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Setup
      run: echo "Setting up for main branch CI"
    
    - name: Validate
      run: echo "Running validation on main branch"